# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "openshell.fullname" . }}-sandbox
  labels:
    {{- include "openshell.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - agents.x-k8s.io
    resources:
      - sandboxes
      - sandboxes/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
