# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# cargo-about configuration for generating third-party license notices.
# See https://embarkstudios.github.io/cargo-about/

# Accepted licenses (SPDX expressions). All permissive/weak-copyleft licenses
# found in this workspace's dependency tree.
accepted = [
    "0BSD",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-1-Clause",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "CC0-1.0",
    "CDLA-Permissive-2.0",
    "ISC",
    "LGPL-2.1-or-later",
    "MIT",
    "MIT-0",
    "OpenSSL",
    "Unicode-3.0",
    "Unlicense",
    "Zlib",
]
