import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { execFileSync } from 'child_process';
import { DEFAULT_CATEGORIES } from '../types.js';
import { hasQmd, withQmdIndexArgs } from '../lib/search.js';

const CONFIG_FILE = '.clawvault.json';

export interface SetupOptions {
  graphColors?: boolean;
  bases?: boolean;
  canvas?: boolean;
  theme?: 'neural' | 'minimal' | 'none';
  force?: boolean;
  vault?: string;
  qmdIndexName?: string;
}

function resolveVaultTarget(vaultOverride?: string): { vaultPath: string; source: string; existed: boolean } {
  if (vaultOverride) {
    const vaultPath = path.resolve(vaultOverride);
    return { vaultPath, source: '--vault flag', existed: fs.existsSync(vaultPath) };
  }

  const envPath = process.env.CLAWVAULT_PATH?.trim();
  const home = os.homedir();
  
  if (envPath) {
    const vaultPath = path.resolve(envPath);
    return { vaultPath, source: 'CLAWVAULT_PATH', existed: fs.existsSync(vaultPath) };
  }
  
  const candidates = [
    { vaultPath: path.join(home, '.openclaw', 'workspace', 'memory'), source: 'OpenClaw default' },
    { vaultPath: path.resolve(process.cwd(), 'memory'), source: './memory' },
    { vaultPath: path.join(home, 'memory'), source: '~/memory' }
  ];
  
  for (const candidate of candidates) {
    if (fs.existsSync(candidate.vaultPath)) {
      return { ...candidate, existed: true };
    }
  }
  
  const fallback = candidates[0];
  return { ...fallback, existed: false };
}

function ensureVaultStructure(vaultPath: string): boolean {
  fs.mkdirSync(vaultPath, { recursive: true });
  for (const category of DEFAULT_CATEGORIES) {
    fs.mkdirSync(path.join(vaultPath, category), { recursive: true });
  }
  const configPath = path.join(vaultPath, CONFIG_FILE);
  if (fs.existsSync(configPath)) return false;
  const now = new Date().toISOString();
  const name = path.basename(vaultPath);
  const meta = {
    name,
    version: '1.0.0',
    created: now,
    lastUpdated: now,
    categories: DEFAULT_CATEGORIES,
    documentCount: 0,
    qmdCollection: name,
    qmdRoot: vaultPath
  };
  fs.writeFileSync(configPath, JSON.stringify(meta, null, 2));
  return true;
}

function writeBases(vaultPath: string, force: boolean): number {
  const basesFiles: Record<string, string> = {
    'all-tasks.base': `filters:
  and:
    - file.inFolder("tasks")
    - status != "done"
formulas:
  age: (now() - file.ctime).days
  status_icon: if(status == "blocked", "🔴", if(status == "in-progress", "🔨", if(status == "open", "⚪", "✅")))
views:
  - type: table
    name: All Active Tasks
    groupBy:
      property: status
      direction: ASC
    order:
      - formula.status_icon
      - file.name
      - status
      - owner
      - project
      - priority
      - blocked_by
      - formula.age
  - type: cards
    name: Task Board
    groupBy:
      property: status
      direction: ASC
    order:
      - file.name
      - owner
      - project
      - priority`,
    'blocked.base': `filters:
  and:
    - file.inFolder("tasks")
    - status == "blocked"
formulas:
  days_blocked: (now() - file.ctime).days
views:
  - type: table
    name: Blocked Tasks
    order:
      - file.name
      - owner
      - project
      - blocked_by
      - formula.days_blocked
      - priority`,
    'by-project.base': `filters:
  and:
    - file.inFolder("tasks")
    - status != "done"
formulas:
  status_icon: if(status == "blocked", "🔴", if(status == "in-progress", "🔨", "⚪"))
views:
  - type: table
    name: By Project
    groupBy:
      property: project
      direction: ASC
    order:
      - formula.status_icon
      - file.name
      - status
      - owner
      - priority
  - type: cards
    name: Project Cards
    groupBy:
      property: project
      direction: ASC
    order:
      - file.name
      - owner
      - status`,
    'by-owner.base': `filters:
  and:
    - file.inFolder("tasks")
    - status != "done"
views:
  - type: table
    name: By Owner
    groupBy:
      property: owner
      direction: ASC
    order:
      - file.name
      - status
      - project
      - priority`,
    'backlog.base': `filters:
  and:
    - file.inFolder("backlog")
views:
  - type: table
    name: Backlog
    order:
      - file.name
      - source
      - project
      - file.ctime`,
  };

  let written = 0;
  for (const [filename, content] of Object.entries(basesFiles)) {
    const filePath = path.join(vaultPath, filename);
    if (force || !fs.existsSync(filePath)) {
      fs.writeFileSync(filePath, content);
      written++;
    }
  }
  return written;
}

const NEURAL_GRAPH_CSS = `/* ClawVault Graph Colors — Neural Neural Style */
/* Auto-generated by \`clawvault setup --theme neural\` */

body.theme-dark .graph-view .graph-view-container { background-color: #0a0a0a; }

body.theme-dark .graph-view .node.tag-person circle { fill: #00b4d8 !important; }
body.theme-dark .graph-view .node.tag-project circle { fill: #2d6a4f !important; }
body.theme-dark .graph-view .node.tag-decision circle { fill: #e8590c !important; }
body.theme-dark .graph-view .node.tag-lesson circle { fill: #fcc419 !important; }
body.theme-dark .graph-view .node.tag-commitment circle { fill: #e03131 !important; }
body.theme-dark .graph-view .node.tag-task circle { fill: #22b8cf !important; }
body.theme-dark .graph-view .node.tag-observation circle { fill: #7950f2 !important; }
body.theme-dark .graph-view .node.tag-handoff circle { fill: #845ef7 !important; }
body.theme-dark .graph-view .node.tag-daily circle { fill: #495057 !important; }

body.theme-dark .graph-view .node.is-focused circle {
  fill: #e8a430 !important; stroke: #e8a430 !important;
  stroke-width: 3px; filter: drop-shadow(0 0 6px #e8a430);
}

body.theme-dark .graph-view .link { stroke: rgba(45, 200, 120, 0.15) !important; }
body.theme-dark .graph-view .link.is-focused { stroke: rgba(45, 200, 120, 0.6) !important; }
body.theme-dark .graph-view .node text { fill: #c1c2c5 !important; font-size: 0.8em; }
`;

const MINIMAL_GRAPH_CSS = `/* ClawVault Graph Colors — Minimal */
/* Auto-generated by \`clawvault setup --theme minimal\` */

body.theme-dark .graph-view .node.tag-person circle { fill: #4a90e8 !important; }
body.theme-dark .graph-view .node.tag-project circle { fill: #4ae85d !important; }
body.theme-dark .graph-view .node.tag-decision circle { fill: #e85d4a !important; }
body.theme-dark .graph-view .node.tag-lesson circle { fill: #9b59b6 !important; }
body.theme-dark .graph-view .node.tag-task circle { fill: #e8a430 !important; }
`;

const NEURAL_COLOR_GROUPS = [
  { query: 'path:people', color: { a: 1, rgb: 47316 } },
  { query: 'path:projects', color: { a: 1, rgb: 2976335 } },
  { query: 'path:decisions', color: { a: 1, rgb: 15227916 } },
  { query: 'path:lessons', color: { a: 1, rgb: 16565273 } },
  { query: 'path:tasks', color: { a: 1, rgb: 2275535 } },
  { query: 'path:commitments', color: { a: 1, rgb: 14680369 } },
  { query: 'path:backlog', color: { a: 1, rgb: 9806262 } },
  { query: 'path:inbox', color: { a: 1, rgb: 15964178 } },
  { query: 'path:handoffs', color: { a: 1, rgb: 8675063 } },
  { query: 'path:ledger', color: { a: 1, rgb: 7950066 } },
];

const MINIMAL_COLOR_GROUPS = [
  { query: 'path:people', color: { a: 1, rgb: 4886760 } },
  { query: 'path:projects', color: { a: 1, rgb: 4909149 } },
  { query: 'path:decisions', color: { a: 1, rgb: 15228234 } },
  { query: 'path:lessons', color: { a: 1, rgb: 10181046 } },
  { query: 'path:tasks', color: { a: 1, rgb: 15246384 } },
];

function writeGraphColors(vaultPath: string, theme: string, force: boolean): boolean {
  const obsidianDir = path.join(vaultPath, '.obsidian');
  if (!fs.existsSync(obsidianDir)) {
    // Not an Obsidian vault — skip silently
    return false;
  }

  const snippetsDir = path.join(obsidianDir, 'snippets');
  fs.mkdirSync(snippetsDir, { recursive: true });

  const snippetName = 'clawvault-graph';
  const snippetPath = path.join(snippetsDir, `${snippetName}.css`);

  if (!force && fs.existsSync(snippetPath)) {
    return false;
  }

  // Write CSS snippet
  const css = theme === 'neural' ? NEURAL_GRAPH_CSS : MINIMAL_GRAPH_CSS;
  fs.writeFileSync(snippetPath, css);

  // Enable snippet in appearance.json
  const appearancePath = path.join(obsidianDir, 'appearance.json');
  let appearance: Record<string, unknown> = {};
  if (fs.existsSync(appearancePath)) {
    try { appearance = JSON.parse(fs.readFileSync(appearancePath, 'utf-8')); } catch { /* ignore */ }
  }
  const snippets = (appearance.enabledCssSnippets as string[]) || [];
  if (!snippets.includes(snippetName)) {
    snippets.push(snippetName);
    appearance.enabledCssSnippets = snippets;
    fs.writeFileSync(appearancePath, JSON.stringify(appearance, null, 2));
  }

  // Configure graph.json colorGroups
  const graphPath = path.join(obsidianDir, 'graph.json');
  let graphConfig: Record<string, unknown> = {};
  if (fs.existsSync(graphPath)) {
    try { graphConfig = JSON.parse(fs.readFileSync(graphPath, 'utf-8')); } catch { /* ignore */ }
  }
  graphConfig.colorGroups = theme === 'neural' ? NEURAL_COLOR_GROUPS : MINIMAL_COLOR_GROUPS;
  if (theme === 'neural') {
    graphConfig.showTags = false;
    graphConfig.showAttachments = false;
    graphConfig.nodeSizeMultiplier = 1.2;
    graphConfig.lineSizeMultiplier = 0.8;
    graphConfig.textFadeMultiplier = 0;
    graphConfig.repelStrength = 10;
    graphConfig.linkDistance = 250;
    graphConfig.centerStrength = 0.5;
  }
  fs.writeFileSync(graphPath, JSON.stringify(graphConfig, null, 2));

  return true;
}

function getQmdConfig(vaultPath: string): { collection: string; root: string } {
  const configPath = path.join(vaultPath, CONFIG_FILE);
  if (fs.existsSync(configPath)) {
    try {
      const meta = JSON.parse(fs.readFileSync(configPath, 'utf-8')) as {
        name?: string;
        qmdCollection?: string;
        qmdRoot?: string;
      };
      return {
        collection: meta.qmdCollection || meta.name || path.basename(vaultPath),
        root: meta.qmdRoot || vaultPath
      };
    } catch {
      return { collection: path.basename(vaultPath), root: vaultPath };
    }
  }
  return { collection: path.basename(vaultPath), root: vaultPath };
}

export async function setupCommand(options: SetupOptions = {}): Promise<void> {
  const target = resolveVaultTarget(options.vault);
  if (target.existed && !fs.statSync(target.vaultPath).isDirectory()) {
    throw new Error(`Vault path is not a directory: ${target.vaultPath}`);
  }
  if (!target.existed) fs.mkdirSync(target.vaultPath, { recursive: true });
  console.log(`${target.existed ? 'Found' : 'Created'} vault path (${target.source}): ${target.vaultPath}`);

  const initialized = ensureVaultStructure(target.vaultPath);
  console.log(initialized ? '✓ Initialized vault structure.' : '✓ Vault structure already present.');

  const force = options.force ?? false;
  const theme = options.theme ?? 'neural';

  // Determine what to set up — if no explicit flags, do everything
  const explicitFlags = options.graphColors !== undefined || options.bases !== undefined || options.canvas !== undefined;
  const doGraphColors = explicitFlags ? (options.graphColors !== false) : true;
  const doBases = explicitFlags ? (options.bases !== false) : true;
  const doCanvas = explicitFlags ? (options.canvas !== undefined && options.canvas !== false) : false;

  // Graph colors
  if (doGraphColors && theme !== 'none') {
    const wrote = writeGraphColors(target.vaultPath, theme, force);
    if (wrote) {
      console.log(`✓ Graph colors configured (${theme} theme)`);
    } else {
      const obsidianDir = path.join(target.vaultPath, '.obsidian');
      if (!fs.existsSync(obsidianDir)) {
        console.log('⊘ No .obsidian directory — skipping graph colors (not an Obsidian vault)');
      } else {
        console.log('⊘ Graph colors already exist (use --force to overwrite)');
      }
    }
  } else if (doGraphColors && theme === 'none') {
    console.log('⊘ Graph colors skipped (--theme none)');
  }

  // Bases
  if (doBases) {
    const count = writeBases(target.vaultPath, force);
    if (count > 0) {
      console.log(`✓ Created ${count} Obsidian Bases view${count > 1 ? 's' : ''}`);
    } else {
      console.log('⊘ Bases views already exist (use --force to overwrite)');
    }
  }

  // Canvas
  if (doCanvas) {
    try {
      const { canvasCommand } = await import('./canvas.js');
      await canvasCommand(target.vaultPath);
    } catch (err) {
      console.log(`⚠ Canvas generation failed: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  // qmd
  if (hasQmd()) {
    const { collection, root } = getQmdConfig(target.vaultPath);
    try {
      execFileSync('qmd', withQmdIndexArgs(['collection', 'add', root, '--name', collection, '--mask', '**/*.md'], options.qmdIndexName), {
        stdio: 'ignore',
        shell: process.platform === 'win32'
      });
      console.log(`✓ qmd collection ready: ${collection}`);
    } catch {
      console.log('⊘ qmd collection already exists.');
    }
  } else {
    console.log('⊘ qmd not found — skipping optional qmd fallback setup.');
  }

  console.log('\nTip: add this to your shell config:');
  console.log(`  export CLAWVAULT_PATH="${target.vaultPath}"`);

  console.log('\nCustomize further:');
  console.log('  clawvault setup --theme neural     # Neural neural graph colors');
  console.log('  clawvault setup --theme minimal        # Subtle category colors');
  console.log('  clawvault setup --canvas                # Generate vault status canvas');
  console.log('  clawvault setup --no-bases --no-graph-colors  # Structure only');
  console.log('  clawvault setup --force                 # Overwrite existing configs');
}
