name: Branch E2E Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

permissions:
  contents: read
  packages: write

jobs:
  build-gateway:
    if: contains(github.event.pull_request.labels.*.name, 'test:e2e')
    uses: ./.github/workflows/docker-build.yml
    with:
      component: gateway
      platform: linux/arm64
      runner: build-arm64

  build-cluster:
    if: contains(github.event.pull_request.labels.*.name, 'test:e2e')
    uses: ./.github/workflows/docker-build.yml
    with:
      component: cluster
      platform: linux/arm64
      runner: build-arm64

  e2e:
    needs: [build-gateway, build-cluster]
    uses: ./.github/workflows/e2e-test.yml
    with:
      image-tag: ${{ github.sha }}
      runner: build-arm64
